# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'FlutterHybridDemo' do
    pod 'Masonry', '~> 1.1.0'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'FlutterModule', :git => 'https://github.com/hhtczengjing/flutter_module_example.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
